
[article]
todos = [
	"author",
	"title",
	"journal",
	"year"
]
optionals = [
	"doi",
	"isbn",
	"issn",
	"metanote",
	"number",
	"numpages",
	"pages",
	"publisher",
	"url",
	"volume"
]
oneof_doi_page = [
    "doi",
    "pages",
    "numpages"
]
oneof_doi_isbn = [
    "doi",
    "isbn"
]
oneof_doi_issn = [
    "doi",
    "issn"
]
oneof_doi_number = [
    "doi",
    "number"
]
oneof_doi_publisher = [
    "doi",
    "publisher"
]
oneof_doi_volume = [
    "doi",
    "volume"
]
oneof_doi_url = [
    "doi",
    "url"
]

[book]
todos = [
	"author",
	"title",
	"publisher",
	"year"
]
optionals = [
	"doi",
	"edition",
	"isbn",
	"issn",
	"metanote",
	"url"
]
oneof_doi_edition = [
    "doi",
    "edition"
]
oneof_doi_isbn = [
    "doi",
    "isbn"
]
oneof_doi_issn = [
    "doi",
    "issn"
]
oneof_doi_publisher = [
    "doi",
    "publisher"
]
oneof_doi_url = [
    "doi",
    "url"
]

[incollection]
todos = [
	"author",
	"title",
	"booktitle",
	"publisher",
	"year"
]
optionals = [
	"doi",
	"isbn",
	"issn",
	"metanote",
	"numpages",
	"pages",
	"url"
]
oneof_doi_page = [
    "doi",
    "pages",
    "numpages"
]
oneof_doi_isbn = [
    "doi",
    "isbn"
]
oneof_doi_issn = [
    "doi",
    "issn"
]
oneof_doi_publisher = [
    "doi",
    "publisher"
]
oneof_doi_url = [
    "doi",
    "url"
]

[inproceedings]
todos = [
	"author",
	"title",
	"booktitle",
	"year"
]
optionals = [
	"doi",
	"isbn",
	"issn",
	"metanote",
	"numpages",
	"pages",
	"publisher",
	"series",
	"url",
	"year"
]
oneof_doi_page = [
    "doi",
    "pages",
    "numpages"
]
oneof_doi_isbn = [
    "doi",
    "isbn"
]
oneof_doi_issn = [
    "doi",
    "issn"
]
oneof_doi_publisher = [
    "doi",
    "publisher"
]
oneof_doi_url = [
    "doi",
    "url"
]

[mastersthesis]
todos = [
	"author",
	"title",
	"school",
	"year"
]
optionals = [
	"metanote",
	"url",
]

[misc]
todos = [
	"author",
	"title",
	"note",
	"url",
	"year"
]
optionals = [
	"institution",
	"metanote"
]

[techreport]
todos = [
	"author",
	"title",
	"institution",
	"year"
]
optionals = [
	"metanote",
	"series",
	"url",
	"version"
]

[unpublished]
todos = [
	"author",
	"title",
	"note",
	"url"
]
optionals = [
	"metanote"
]

[phdthesis]
todos = [
	"author",
	"title",
	"school",
	"year"
]
optionals = [
	"metanote",
	"url",
]

[default]
todos = [
	"title"
]
optionals = [
]
